New api proposal (review in depth requested)
MinecraftModDevelopment/OreSpawn pull request #46
Opened 2017-07-05 00:13 UTC by dshadowwolf

Adds a new annotation based API
Updates to version 1.1 of the json format
Adds biome blacklisting and biome dictionary support
Stops the code from creating the OS1 config directory if it doesn't exist
Preparations in place for the next run of updates

2017-07-05 00:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftModDevelopmentMods/OreSpawn?pullRequest=46) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftModDevelopmentMods/OreSpawn?pullRequest=46) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dshadowwolf<br/>:x: pau101<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftModDevelopmentMods/OreSpawn?pullRequest=46) it.</sub>

2017-07-05 00:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftModDevelopmentMods/OreSpawn?pullRequest=46) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftModDevelopmentMods/OreSpawn?pullRequest=46) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dshadowwolf<br/>:x: pau101<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftModDevelopmentMods/OreSpawn?pullRequest=46) it.</sub>

2017-07-05 01:07 UTC, pau101 requested changes

2017-07-05 01:07 UTC, pau101 commented on src/main/java/com/mcmoddev/orespawn/impl/os3/OS3APIImpl.java
> +	private final Map<String, BuilderLogic> logic;
My builder suggestion was to only hold immutable objects which contain the data for generation. Nothing has been done to implement that besides renaming the classes.

2017-07-05 01:07 UTC, pau101 commented on src/main/java/com/mcmoddev/orespawn/api/os3/BuilderLogic.java
> +	DimensionBuilder DimensionBuilder(); // literally all dimensions
I would not have uppercase methods names. `newDimensionBuilder` would be conventional. Also you have @​Nonnull on primitive.

2017-07-05 01:07 UTC, pau101 commented on src/main/java/com/mcmoddev/orespawn/api/os3/DimensionBuilder.java
> +  SpawnBuilder SpawnBuilder( @Nullable String name );
Uppercase method name, `newSpawnBuilder` would be conventional.

2017-07-05 01:07 UTC, pau101 commented on src/main/java/com/mcmoddev/orespawn/api/os3/SpawnBuilder.java
> +	OreBuilder OreBuilder();
Uppercase method names, `newFeatureBuilder`, `newBiomeBuilder`, and `newOreBuilder` would be conventional.

2017-07-05 01:07 UTC, pau101 commented on src/main/java/com/mcmoddev/orespawn/impl/os3/BuilderLogicImpl.java
> +		switch(name.toLowerCase()) {
Should be locale insensitive: `name.toLowerCase(Locale.ROOT)`

2017-07-05 01:07 UTC, pau101 commented on src/main/java/com/mcmoddev/orespawn/impl/os3/BuilderLogicImpl.java
> +		switch(name.toLowerCase()) {
Should be locale insensitive: `name.toLowerCase(Locale.ROOT)`

2017-07-05 01:07 UTC, pau101 commented on src/main/java/com/mcmoddev/orespawn/json/OS1Reader.java
> +		                	} else if( dim.get("dimension").getAsString() == ""+dim.get("dimension").getAsInt() ) {
String equality comparison with `==`, but more importantly this is not the way to check if the element is a number. The condition should be ` dim.get("dimension").isJsonPrimitive() && dim.get("dimension").getAsJsonPrimitive().isNumber()`, but `dim.get("dimension")` should be done once and stored in a variable before this if/else series.

2017-07-05 01:07 UTC, pau101 commented on src/main/java/com/mcmoddev/orespawn/api/plugin/PluginLoader.java
> +							reader.close();
This finally block can be replaced with `IOUtils.close(reader);`

2017-07-05 01:07 UTC, pau101 commented on src/main/java/com/mcmoddev/orespawn/impl/os3/OS3APIImpl.java
> +        	OreSpawn.LOGGER.info("Registered spawn logic for mod " + ent.getKey());
Change to: `OreSpawn.LOGGER.info("Registered spawn logic for mod {}", ent.getKey());`

2017-07-05 01:07 UTC, pau101 commented on src/main/java/com/mcmoddev/orespawn/api/plugin/IOreSpawnPlugin.java
> +@FunctionalInterface
@​FunctionalInterface isn't appropriate here.

2017-07-05 04:37 UTC, dshadowwolf commented
latest patch added to this PR/review set makes sure the API is functional and disables the "load from a resource location" code as it is apparently bad/doesn't work - looks like the functionality for it was not patched in until Forge started working with the recipe stuff in 1.12

2017-07-05 05:50 UTC, dshadowwolf commented
latest added patch-set adds a plugin to the code-base for registering vanilla ores (proving that it works) and fixes a lot of misc bugs.

2017-07-05 09:13 UTC, dshadowwolf commented
And that patch, hopefully, gets resource-loading working

2017-07-05 10:24 UTC, dshadowwolf commented
last couple patch sets have gotten the "plugins can have data in their jar files and we can copy them out and use them" issue handled - that code should be relatively stable.

2017-07-06 02:20 UTC, dshadowwolf commented
Last commit added to this set removes all warnings from the Java side of things and all but 2 issues from SonarLint (so far) - SonarQube is likely to still have quite a bit after this is merged.

2017-07-06 17:02 UTC, jriwanek requested changes
I didn't tag *every* case where there's strings which should be constants for reuse throughout the code, but sharing them all is the intent.

2017-07-06 17:02 UTC, jriwanek commented on src/main/java/com/mcmoddev/orespawn/commands/AddOreCommand.java
>          ore.addProperty("size", 25);
We should probably extend addore so size et al can be specified as part of the command, or defaulted to as shown if not provided

2017-07-06 17:02 UTC, jriwanek commented on src/main/java/com/mcmoddev/orespawn/impl/os3/BuilderLogicImpl.java
> +		case "overworld":
make "overworld", "the nether" and "the end" shared constants, also provide "the overworld", "nether" and "end" for consistency.

2017-07-06 17:02 UTC, jriwanek commented on src/main/java/com/mcmoddev/orespawn/json/OS1Reader.java
> +		                	JsonElement dimElem = dim.get("dimension");
"dimension" and "ores" should really be shared constants.

2017-07-06 17:02 UTC, jriwanek commented on src/main/java/com/mcmoddev/orespawn/json/OS1Reader.java
> +			String blockID = ore.get("blockID").getAsString();
"blockID" should be a shared constant.

2017-07-06 17:02 UTC, jriwanek commented on src/main/java/com/mcmoddev/orespawn/json/OS1Reader.java
> +			int meta = ore.has("metaData")?ore.get("metaData").getAsInt():0;
"metaData" should be a shared constant.

2017-07-06 17:02 UTC, jriwanek commented on src/main/java/com/mcmoddev/orespawn/json/OS1Reader.java
> +			float frequency = ore.has("frequency")?ore.get("frequency").getAsFloat():20.0f;
"frequency", "minHeight", "maxHeight", "variation", "default" and "size" should be shared constants

2017-07-06 17:02 UTC, jriwanek commented on src/main/java/com/mcmoddev/orespawn/json/OS1Reader.java
> +				for( JsonElement bm : ore.get("biomes").getAsJsonArray() ) {
"biomes" should be a shared constant

2017-07-06 17:02 UTC, jriwanek commented on src/main/java/com/mcmoddev/orespawn/json/OS2Reader.java
> +		                    int dimension = object.has("dimension") ? object.get("dimension").getAsInt() : OreSpawn.API.dimensionWildcard();
"dimension" should be a shared constant.

2017-07-06 18:12 UTC, Darkhax reviewed
Mostly good, as Jas said using constants will help improve the maintainability of the code. I think the builder pattern may be a bit overboard here, and JavaDocs are in order, however I believe those are outside the scope for this review.

2017-07-07 02:08 UTC, jriwanek approved these changes

2017-07-07 02:11 UTC, merged